django_blog/accounts/urls.py
from django.conf.urls import url
from.import views


app_name = 'accounts'

urlpatterns = [
url(r'^signup/$', views.signup_view, name= 'signup'),
url(r'^login/$', views.login_view, name= 'login'),
url(r'^logout/$',views.logout_view, name= 'logout')

]

django_blog/articles/urls.py
from django.conf.urls import url
from.import views

app_name='articles'

urlpatterns = [

    url(r'^$', views.articles_list, name ='list'),
    url(r'^create/$', views.article_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='detail'),
    
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^$',views.homepage),
    url(r'^about/$',views.about),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

django_blog/accounts/models.py
from django.db import models

# Create your models here.

django_blog/articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)


def __str__(self):
    return self.title

def snippet(self):
    return self.body [:50] + '...'    
   


 

# Create your models here.

django_blog/articles/forms.py
from django import forms
from.import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model= models.Article
        fields= ['title','body', 'slug', 'thumb']

django_blog/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


def signup_view(request):

  if request.method =='POST':

     form = UserCreationForm(request.POST)
     
     if form.is_valid():
      
      user=form.save() 
      login(request, user)
         #log the user in
     return redirect('articles:list')
  else:      
     form = UserCreationForm()
  return render(request, 'accounts/signup.html', {'form':form})
  

def login_view(request):
  if request.method =='POST':
     form = AuthenticationForm(data= request.POST)
     if form.is_valid():
        #log the user in
        user = form.get_user()
        login(request, user)
        if 'next' in request.POST:
            return redirect(request.POST.get('next')) 
        else:
            return redirect('articles:list')

  else:
     form=AuthenticationForm()
  return render(request,'accounts/login.html', {'form':form})   


def logout_view(request):
   if request.method == 'POST':
      logout(request)
      return redirect('articles:list')

# Create your views here.

django_blog/articles/views.py
from django.shortcuts import render,redirect
from.models import Article
from django.contrib.auth.decorators import login_required
from.import forms


def articles_list(request):
    articles = Article.objects.all().order_by('date')    
    return render(request, 'articles/articles_list.html',{'articles': articles})
def article_detail(request, slug):   
   article = Article.objects.get(slug=slug)
   return render(request, 'articles/article_detail.html', {'article' : article})
@login_required(login_url = '/accounts/login/')
def article_create(request):
  if request.method == 'POST':
       form=forms.CreateArticle(request.POST,request.FILES)
       if form.is_valid:
        # save to db
        return redirect('articles:list')
  else:
    form=forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form})
# Create your views here.

django_blog/django_blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
   # return HttpResponse("Welcome to my homepage")
   return render(request, 'homepage.html')

def about(request):
    #return HttpResponse("about")
    return render(request,'about.html')

def articles_list(request):
   return render(request,'')

django_blog/accounts/templates/accounts/login.html
{% extends 'global.html' %}

{% block content %}

<h1>This is a simple login page testing</h1>
 <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
    {% if request.GET.next %}
     <input type="hidden" name="next" value="{{ request.GET.next }}">
     {% endif %}
    {% csrf_token %}
    {{form}}
  <button type="'Submit"> login</button>
 </form>

{% endblock %}

django_blog/accounts/templates/accounts/signup.html
{% extends 'global.html' %}

{% block content %}

<h1>This is a simple signup page testing</h1>
 <form class="site-form" action="/accounts/signup/" method="post">
 {% csrf_token %}
 {{form}}
 <button type="submit">Sign up</button>
</form>

{% endblock %}

django_blog/articles/templates/articles/article_create.html
{% extends 'global.html' %}

{% block content %}
<div class="create">

    <h1>Create an Awesome article for everyone to see </h1>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="Submit">Create</button>
    </form>
</div>


{% endblock %}

django_blog/articles/templates/articles/article_detail.html
{% extends 'global.html'%}

{% block forged %}

<div class="article-deatil">
<div class="article">
<img src="{{article.thumb.url}}"/>
<h2>{{article.title}}</h2>
<p>{{ article.body}}</p>
<p>{{ article.date}}</p>  

</div>

</div>

{% endblock %}

django_blog/articles/templates/articles/articles_list.html
   {% extends 'global.html'%}

   {% block content %}
    <p>This is an article page</p>
    <div class="articles">
        {% for article in articles %}
    <div class="article">
         <h1><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h1>
        <h1><a href="#">{{article.title}}</a></h1>
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
    </div>
        {%endfor%}
    </div>
    {% endblock %}

django_blog/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>This is an about us page</p>
</body>
</html>

django_blog/templates/global.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
  <header class="game changer">
    <h2> <a href="{% url 'articles:list' %}">Please Welcome</a> </h2>
    <nav>
      <ul>
        <li>
          <form class="logout-link" action=" {% url 'accounts:logout' %}" method ="post" >
            {% csrf_token %}
            <button type="submit">logout</button>
          </form>
        </li>
      </ul>
    </nav>
  </header>
  <div class="game changer">

   {% block content %}
   {% endblock %}

   {% block forged%}
   {% endblock %}

  </div>
</body>
</html>

django_blog/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Welcome to a django beginner homepage</p>
</body>
</html>

 